# Generated by Django 5.2.6 on 2026-09-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(default='120/80', max_length=20)),
                ('heart_rate', models.IntegerField(default=75)),
                ('temperature', models.DecimalField(decimal_places=1, default=98.6, max_digits=5)),
                ('spo2', models.IntegerField(default=98)),
                ('blood_sugar', models.IntegerField(default=100)),
                ('respiratory_rate', models.IntegerField(default=16)),
                ('recorded_by', models.CharField(blank=True, default='Nurse', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
