# Generated by Django 5.2.5 on 2026-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('report_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
