# Generated by Django 6.0.8 on 2026-09-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_unique_doctor_appointment_slot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
    ]
