# Generated by Django 5.2.5 on 2026-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
